<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateurs extends \App\Entity\Utilisateurs implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'formation', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'civilite', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'villes', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'departement', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'login', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'message_envoyer', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'message_recu', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'activites'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'formation', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'date_de_naissance', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'civilite', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'villes', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'departement', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'login', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'message_envoyer', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'message_recu', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Utilisateurs' . "\0" . 'activites'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateurs $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(?string $email): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(?string $role): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$role]);

        return parent::setRoles($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormation', []);

        return parent::getFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormation(?string $formation): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormation', [$formation]);

        return parent::setFormation($formation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(?string $nom): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(?string $prenom): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', []);

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance(?\DateTimeInterface $date_de_naissance): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', [$date_de_naissance]);

        return parent::setDateDeNaissance($date_de_naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(?string $adresse): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(?string $code_postal): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$code_postal]);

        return parent::setCodePostal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilles(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilles', []);

        return parent::getVilles();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilles(?string $villes): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilles', [$villes]);

        return parent::setVilles($villes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(?string $pays): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(?string $telephone): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', []);

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivilite(?string $civilite): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', [$civilite]);

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin(string $login): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$login]);

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug(?string $slug): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function isVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVerified', []);

        return parent::isVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVerified(bool $isVerified): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVerified', [$isVerified]);

        return parent::setIsVerified($isVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageEnvoyer(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageEnvoyer', []);

        return parent::getMessageEnvoyer();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessageEnvoyer(\App\Entity\Messages $messageEnvoyer): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessageEnvoyer', [$messageEnvoyer]);

        return parent::addMessageEnvoyer($messageEnvoyer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessageEnvoyer(\App\Entity\Messages $messageEnvoyer): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessageEnvoyer', [$messageEnvoyer]);

        return parent::removeMessageEnvoyer($messageEnvoyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageRecu(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageRecu', []);

        return parent::getMessageRecu();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessageRecu(\App\Entity\Messages $messageRecu): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessageRecu', [$messageRecu]);

        return parent::addMessageRecu($messageRecu);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessageRecu(\App\Entity\Messages $messageRecu): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessageRecu', [$messageRecu]);

        return parent::removeMessageRecu($messageRecu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', []);

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\App\Entity\Medias $media): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', [$media]);

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\App\Entity\Medias $media): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', [$media]);

        return parent::removeMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\App\Entity\Contacts $contact): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', [$contact]);

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\App\Entity\Contacts $contact): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', [$contact]);

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivites(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivites', []);

        return parent::getActivites();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivite(\App\Entity\Activites $activite): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivite', [$activite]);

        return parent::addActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivite(\App\Entity\Activites $activite): \App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivite', [$activite]);

        return parent::removeActivite($activite);
    }

}
