<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8dyLTxf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8dyLTxf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8dyLTxf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8dyLTxf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8dyLTxf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8dyLTxf',
    'container.build_id' => 'e3e36c88',
    'container.build_time' => 1647378013,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8dyLTxf');
