<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR2J46zt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR2J46zt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR2J46zt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR2J46zt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR2J46zt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R2J46zt',
    'container.build_id' => '9f1476be',
    'container.build_time' => 1656978701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR2J46zt');
