<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLwOKdh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLwOKdh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLwOKdh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLwOKdh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZLwOKdh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZLwOKdh',
    'container.build_id' => '0f95017d',
    'container.build_time' => 1648995895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLwOKdh');
